services:
  - type: web
    name: uzoca-app
    env: php
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php -S 0.0.0.0:$PORT -t .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: uzoca-db
          property: connectionString
      - key: DB_HOST
        fromDatabase:
          name: uzoca-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: uzoca-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: uzoca-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: uzoca-db
          property: password
      - key: DB_PORT
        fromDatabase:
          name: uzoca-db
          property: port

databases:
  - name: uzoca-db
    databaseName: uzoca
    user: uzoca_user
